### ISSUE TITLE
Permission Changes Panel Terminology incorrect

### ISSUE THREAD

**Issue by DawtCom** [ForgeEssentials/FERemotePanel#1]
I have fixed this locally and would love to contribute

**Comment by olee** [comment]
Same as #2 - can you describe the problem a bit more - and a PR to show what you changed would be better :sweat_smile:

**Comment by DawtCom** [comment]
I will check out a version and branch it so you can pull changes in.  Sorry been gone for a while.

**Comment by DawtCom** [comment]
Closed.  See pull request, issue 3.
