### ISSUE TITLE
Group Permissions not allowing updates

### ISSUE THREAD

**Issue by DawtCom** [ForgeEssentials/FERemotePanel#2]
I also have fixed this in the angular code and am curious how you would like to merge this.

**Comment by olee** [comment]
Ehm... there was a problem with that?
Could you please describe, what you actually did?
And you might want to open a pull request instead if you actually have some fix coded already.

**Comment by olee** [comment]
Oh I tested it again and you are right - player permissions are changeable, but not group permissions.
Can you make a PR?

**Comment by olee** [comment]
Fixed in https://github.com/ForgeEssentials/FERemotePanel/commit/6866a58de69166902d5118e18a49d55214ae46a2

**Comment by DawtCom** [comment]
Sorry about this.  I have been busy over the last week.  Thanks for fix.  I will test and compare to my version.

**Comment by olee** [comment]
Yeah I changed some stuff to make permissions sorted and did it only for user permissions completely and forgot to update all of it for groups.
