### ISSUE TITLE
does this still work?

### ISSUE THREAD

**Issue by nightstalker6669** [ForgeEssentials/FERemotePanel#4]
I was playing with this in hopes of finding an easier way of adding in permissions, as i have alot of perms to do. but it doesn't seem to do anything. the closet i got it to working was [this](http://puu.sh/nQhO7/5c8cecc057.png) but everything i click on goes to a blank page. perhaps i have something set wrong, but it doesn't seem to want to do anything for me.

**Comment by olee** [comment]
Hm... looks like some resources are missing...
This panel indeed still works ... I just haven't worked on it for a little while.
It looks like on your server the `<base>` tag is generated incorrectly:

```
<base href="//">
```

Because of that it cannot load any resources.
I might have some bug in the code detecting the webpage root.
Try putting the whole thing into a subfolder and accessing it again.

**Comment by nightstalker6669** [comment]
ok heres my setup just so i can paint a clear picture. for the purposes of this test, the document root directory for my apache server is /var/www/html/. when i moved the whole FERemotepanel folder to /var/www/html/remote/ then attempted to log into the remote via webhost.com/remote/FERemotePanel/web/app.php i'm taken to [this page](http://puu.sh/nQlIv/fa697eb5b3.png). now when i attempt to log in, i get [this page](http://puu.sh/nQlLR/1b2f7a4762.png)

**Comment by nightstalker6669** [comment]
applied your fix, and that worked for making it work with the document root set as the web folder. but login problem still persists [here](http://puu.sh/nQmNI/92b03ce1d9.png) and when you try to hit the back button on the browser, it will attempt to go back to folder webhost.com/module/dashboard

**Comment by adamk33n3r** [comment]
@nightstalker6669 do you have `mod_rewrite` enabled on your apache?

**Comment by nightstalker6669** [comment]
it is now. sorry apache isn't my strong point. now it will let me put in my login details, and sends me back to the main screen, briefly flashes the server log window, and then goes back to [this](http://puu.sh/nQnGb/e8a0d7cd0b.png) and none of the buttons except for the login button will do anything.

**Comment by adamk33n3r** [comment]
I'm actually not using apache so I can't help you _much_. I'm trying to get it to work with nginx......not going so well.

But what may be helpful is if you push CTRL-SHIFT-J and reload the page. It may show you some errors in red.

**Comment by nightstalker6669** [comment]
and here is the output from that. [pastebin](http://pastebin.com/g1DzLAxt)

here is me clicking through all the buttons. [pastebin](http://pastebin.com/cKBfjkJT)

**Comment by adamk33n3r** [comment]
Ah. I'm actually getting that same error. For some reason the routes aren't working for getting the views. Maybe @olee knows something more. I'll keep digging.

**Comment by nightstalker6669** [comment]
ok thanks, i'll keep an eye on this.

**Comment by adamk33n3r** [comment]
@nightstalker6669 you could try putting it in a subdirectory again and see if that works. This project seems to be under the assumption that you're running this in a sub directory.

**Comment by nightstalker6669** [comment]
yep, putting it back into the subdirectory seems to fix all the issues. good catch!

**Comment by adamk33n3r** [comment]
Cool! I'll probably still look into fixing it so you don't have to put it in a subdirectory. But I'll make a new issue for that.

**Comment by nightstalker6669** [comment]
awesome! thanks for the help, this will definitely make things easier.
